from tkinter import *
raiz = Tk()
raiz.title("Programa Grafico")
raiz.iconbitmap("perros-pug.ico")
raiz.resizable(1, 1)
raiz.config(bg=("Blue"))
raiz.config(cursor="hand2")
Miframe = Frame()
Miframe.pack()
raiz.mainloop()
print("")