from tkinter import*
raiz=Tk()
raiz.title("Programa Grafico")
raiz.resizable(1,1)
raiz.config(bg=("Blue"))
raiz.config(cursor="hand2")
Miframe=Frame()
Miframe.pack()
Miframe.config(bg=("Green"))
Miframe.config(width="1000",height="500")
Miframe.config(bd=10)
Miframe.config(relief="groove")
Miframe.config(cursor="pirate")
raiz.mainloop()
print("Hola mundo")
